dataSources:
  ds0: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shard01?autoReconnect=true&useSSL=false
    username: shard01
    password: shard01
    maxTotal: 30
  ds1: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shard02?autoReconnect=true&useSSL=false
    username: shard02
    password: shard02
    maxTotal: 30

shardingRule:
  tables:
    user: 
      actualDataNodes: ds${0..1}.user
      databaseStrategy:
        standard:
          shardingColumn: userid
          preciseAlgorithmClassName: net.gywn.algorithm.PreciseShardingCRC32
  bindingTables:
  - user
  broadcastTables:
  - config
  defaultDataSourceName: ds0

props:
  sql.show: false
